export {
  AuthApiClientError,
  authService,
  checkUsernameAvailability,
  getAuthSession,
  getUsernameSuggestions,
  isAuthApiClientError,
  registerUser,
  requestPasswordReset,
  resendVerificationCode,
  resetPassword,
  signInAdmin,
  signInUser,
  signOut,
  verifyPasswordResetCode,
  verifyUserEmail,
} from "./auth.service";

export type {
  AuthAccountData,
  AuthApiRequestOptions,
  AuthSessionResponseData,
  PasswordResetCodeResponseData,
  PasswordResetRequestResponseData,
  PasswordResetResponseData,
  RegisterUserResponseData,
  ResendVerificationCodeInput,
  SignInResponseData,
  SignOutResponseData,
  UsernameAvailabilityResponseData,
  UsernameSuggestionsInput,
  UsernameSuggestionsResponseData,
  VerifyEmailResponseData,
} from "./auth.service";