import type { AssistantKnowledgeItem } from "@/types/assistant";

export const ASSISTANT_KNOWLEDGE_ES = [
  {
    id: "es-general-fixora",
    locale: "es",
    section: "general",
    title: "¿Qué es Fixora?",
    summary:
      "Fixora es una plataforma orientada a soluciones tecnológicas, recursos digitales y asistencia técnica.",
    content:
      "Fixora reúne recursos gráficos, software y licencias, productos de hardware, servicios técnicos, soporte remoto, planes, promociones, contenido de ayuda y orientación sobre el uso de cuentas. Su objetivo es facilitar el acceso a soluciones tecnológicas desde una sola plataforma.",
    keywords: [
      "fixora",
      "qué es fixora",
      "que es fixora",
      "plataforma",
      "tecnología",
      "tecnologia",
      "soluciones tecnológicas",
      "soluciones tecnologicas",
      "servicios",
      "productos",
      "cuenta fixora",
      "autenticación",
      "autenticacion",
    ],
    href: "/",
    priority: 10,
  },
  {
    id: "es-sobre-fixora",
    locale: "es",
    section: "about",
    title: "Sobre Fixora",
    summary:
      "Información general sobre la identidad, propósito y propuesta de Fixora.",
    content:
      "La sección Sobre Fixora presenta la identidad de la plataforma, su propósito y la forma en que organiza sus soluciones tecnológicas. Fixora busca ofrecer una experiencia clara, moderna y accesible para encontrar productos, recursos digitales y servicios técnicos.",
    keywords: [
      "sobre fixora",
      "nosotros",
      "quiénes somos",
      "quienes somos",
      "empresa",
      "propósito",
      "proposito",
      "misión",
      "mision",
      "visión",
      "vision",
    ],
    href: "/sobre-fixora",
    priority: 9,
  },
  {
    id: "es-recursos-graficos",
    locale: "es",
    section: "graphic-resources",
    title: "Recursos gráficos",
    summary:
      "Espacio para explorar recursos visuales gratuitos, de pago y de exhibición.",
    content:
      "La sección Recursos Gráficos está destinada a imágenes y materiales visuales. Puede incluir recursos disponibles para compra, recursos gratuitos y diseños publicados únicamente para observación o inspiración. La disponibilidad y las condiciones de uso se mostrarán en la ficha de cada recurso.",
    keywords: [
      "recursos gráficos",
      "recursos graficos",
      "imágenes",
      "imagenes",
      "diseños",
      "diseños gráficos",
      "diseños graficos",
      "imágenes gratis",
      "imagenes gratis",
      "imágenes de pago",
      "imagenes de pago",
      "comprar imágenes",
      "comprar imagenes",
    ],
    href: "/recursos-graficos",
    priority: 9,
  },
  {
    id: "es-software-licencias",
    locale: "es",
    section: "software-licenses",
    title: "Software y licencias",
    summary:
      "Información sobre programas, herramientas digitales y licencias disponibles.",
    content:
      "La sección Software y Licencias reúne información sobre programas, herramientas digitales y opciones de licenciamiento. Antes de adquirir una licencia, se recomienda revisar su compatibilidad, duración, número de dispositivos y condiciones de activación.",
    keywords: [
      "software",
      "licencias",
      "programas",
      "instalación de programas",
      "instalacion de programas",
      "activar software",
      "activación",
      "activacion",
      "licencia digital",
      "programas para computadora",
      "programas para pc",
    ],
    href: "/software-licencias",
    priority: 9,
  },
  {
    id: "es-hardware",
    locale: "es",
    section: "hardware",
    title: "Hardware",
    summary:
      "Sección dedicada a equipos, componentes, accesorios y productos tecnológicos.",
    content:
      "La sección Hardware está orientada a equipos, componentes, periféricos y accesorios tecnológicos. La información específica de cada producto, como compatibilidad, características, disponibilidad y garantía, deberá consultarse en su publicación correspondiente.",
    keywords: [
      "hardware",
      "equipos",
      "componentes",
      "computadoras",
      "pc",
      "laptop",
      "accesorios",
      "periféricos",
      "perifericos",
      "repuestos",
      "productos tecnológicos",
      "productos tecnologicos",
    ],
    href: "/hardware",
    priority: 8,
  },
  {
    id: "es-servicios-tecnicos",
    locale: "es",
    section: "technical-services",
    title: "Servicios técnicos",
    summary:
      "Asistencia para mantenimiento, formateo, instalación y revisión de equipos.",
    content:
      "Fixora contempla servicios técnicos relacionados con computadoras y otros equipos tecnológicos. Estos servicios pueden incluir mantenimiento preventivo, revisión de fallas, formateo, optimización e instalación de programas. El diagnóstico y el alcance final dependen del estado y las características de cada equipo.",
    keywords: [
      "servicios técnicos",
      "servicios tecnicos",
      "mantenimiento",
      "mantenimiento de computadora",
      "formateo",
      "formatear pc",
      "reparación",
      "reparacion",
      "optimización",
      "optimizacion",
      "instalar programas",
      "revisión de computadora",
      "revision de computadora",
    ],
    href: "/servicios-tecnicos",
    priority: 10,
  },
  {
    id: "es-soporte-remoto",
    locale: "es",
    section: "remote-support",
    title: "Soporte remoto",
    summary:
      "Atención técnica a distancia para revisar y resolver problemas de software.",
    content:
      "El soporte remoto permite recibir asistencia técnica a distancia cuando el problema puede revisarse mediante una conexión autorizada. Es útil para configuraciones, instalación de programas, errores de software y orientación técnica. El usuario debe autorizar la conexión y no debe compartir contraseñas personales, códigos de verificación, tokens de sesión ni información bancaria.",
    keywords: [
      "soporte remoto",
      "ayuda remota",
      "asistencia remota",
      "control remoto",
      "reparación remota",
      "reparacion remota",
      "problemas de software",
      "configuración",
      "configuracion",
      "ayuda a distancia",
      "seguridad soporte remoto",
    ],
    href: "/soporte-remoto",
    priority: 10,
  },
  {
    id: "es-planes-promociones",
    locale: "es",
    section: "plans-promotions",
    title: "Planes y promociones",
    summary:
      "Espacio para consultar paquetes, beneficios y promociones vigentes.",
    content:
      "La sección Planes y Promociones mostrará paquetes, descuentos y beneficios disponibles en Fixora. Los precios, fechas, condiciones y disponibilidad deben verificarse directamente en cada promoción publicada, ya que pueden cambiar.",
    keywords: [
      "planes",
      "promociones",
      "ofertas",
      "descuentos",
      "paquetes",
      "precios",
      "beneficios",
      "promoción vigente",
      "promocion vigente",
      "ofertas fixora",
    ],
    href: "/planes-promociones",
    priority: 8,
  },
  {
    id: "es-cuentas-autenticacion",
    locale: "es",
    section: "help-center",
    title: "Cuentas, acceso y seguridad",
    summary:
      "Orientación sobre registro, inicio de sesión, verificación de correo, recuperación de contraseña y acceso administrativo.",
    content:
      "El asistente de Fixora puede explicar cómo crear una cuenta de usuario, comprobar un nombre público, iniciar sesión, verificar el correo y recuperar una contraseña. El registro público es únicamente para usuarios; las cuentas administrativas son creadas por la empresa y requieren un correo real. El asistente no registra cuentas, no reserva nombres, no inicia sesiones y no cambia contraseñas. Nunca se deben enviar contraseñas reales, códigos de seis caracteres, enlaces privados ni tokens de sesión dentro del chat.",
    keywords: [
      "crear cuenta",
      "registrarme",
      "registro de usuario",
      "iniciar sesión",
      "iniciar sesion",
      "acceder a mi cuenta",
      "nombre de usuario",
      "nombre público",
      "nombre publico",
      "usuario disponible",
      "verificar correo",
      "código de verificación",
      "codigo de verificacion",
      "reenviar código",
      "reenviar codigo",
      "olvidé mi contraseña",
      "olvide mi contraseña",
      "recuperar contraseña",
      "restablecer contraseña",
      "acceso administrador",
      "cuenta administrativa",
      "contraseña segura",
      "contrasena segura",
    ],
    priority: 12,
  },
  {
    id: "es-centro-ayuda",
    locale: "es",
    section: "help-center",
    title: "Centro de Ayuda",
    summary:
      "Sección para resolver dudas frecuentes sobre productos, servicios, cuentas y uso de Fixora.",
    content:
      "El Centro de Ayuda está destinado a responder preguntas frecuentes, explicar procesos y orientar al usuario sobre productos, servicios, compras, soporte, cuentas y funcionamiento de la plataforma. Cuando una respuesta requiera revisar un caso particular, será necesario comunicarse mediante la sección Contacto.",
    keywords: [
      "centro de ayuda",
      "ayuda",
      "preguntas frecuentes",
      "preguntas",
      "dudas",
      "soporte",
      "cómo funciona",
      "como funciona",
      "orientación",
      "orientacion",
      "ayuda con mi cuenta",
      "problema de acceso",
    ],
    href: "/centro-de-ayuda",
    priority: 9,
  },
  {
    id: "es-contacto",
    locale: "es",
    section: "contact",
    title: "Contacto",
    summary:
      "Canal para realizar consultas específicas y solicitar atención personalizada.",
    content:
      "La sección Contacto permite enviar consultas relacionadas con productos, recursos, licencias, servicios técnicos, soporte remoto y problemas de cuenta que necesiten revisión humana. Los datos oficiales de atención y los medios disponibles se mostrarán dentro de esa sección. El asistente no debe inventar números telefónicos, correos, horarios ni direcciones que no estén publicados.",
    keywords: [
      "contacto",
      "contactar",
      "comunicarme",
      "atención",
      "atencion",
      "asesor",
      "teléfono",
      "telefono",
      "correo",
      "whatsapp",
      "dirección",
      "direccion",
      "ayuda humana",
      "problema con mi cuenta",
    ],
    href: "/contacto",
    priority: 10,
  },
] as const satisfies readonly AssistantKnowledgeItem[];