import type { AssistantKnowledgeItem } from "@/types/assistant";

export const ASSISTANT_KNOWLEDGE_EN = [
  {
    id: "en-general-fixora",
    locale: "en",
    section: "general",
    title: "What is Fixora?",
    summary:
      "Fixora is a platform focused on technology solutions, digital resources and technical assistance.",
    content:
      "Fixora brings together graphic resources, software and licenses, hardware products, technical services, remote support, plans, promotions, help content and account guidance. Its purpose is to make technology solutions easier to find from a single platform.",
    keywords: [
      "fixora",
      "what is fixora",
      "platform",
      "technology",
      "technology solutions",
      "services",
      "products",
      "digital resources",
      "technical assistance",
      "fixora account",
      "authentication",
    ],
    href: "/",
    priority: 10,
  },
  {
    id: "en-about-fixora",
    locale: "en",
    section: "about",
    title: "About Fixora",
    summary:
      "General information about Fixora's identity, purpose and value proposition.",
    content:
      "The About Fixora section presents the platform's identity, purpose and the way its technology solutions are organized. Fixora aims to provide a clear, modern and accessible experience for finding products, digital resources and technical services.",
    keywords: [
      "about fixora",
      "about us",
      "who we are",
      "company",
      "purpose",
      "mission",
      "vision",
      "identity",
    ],
    href: "/about-fixora",
    priority: 9,
  },
  {
    id: "en-graphic-resources",
    locale: "en",
    section: "graphic-resources",
    title: "Graphic resources",
    summary:
      "A space for exploring free, paid and display-only visual resources.",
    content:
      "The Graphic Resources section is intended for images and visual materials. It may include resources available for purchase, free resources and designs published only for viewing or inspiration. Availability and usage conditions will be shown on each resource page.",
    keywords: [
      "graphic resources",
      "images",
      "designs",
      "graphic designs",
      "free images",
      "paid images",
      "buy images",
      "visual resources",
      "digital designs",
    ],
    href: "/graphic-resources",
    priority: 9,
  },
  {
    id: "en-software-licenses",
    locale: "en",
    section: "software-licenses",
    title: "Software and licenses",
    summary:
      "Information about programs, digital tools and available licenses.",
    content:
      "The Software and Licenses section provides information about programs, digital tools and licensing options. Before purchasing a license, users should review its compatibility, duration, number of supported devices and activation conditions.",
    keywords: [
      "software",
      "licenses",
      "programs",
      "software installation",
      "install programs",
      "activate software",
      "activation",
      "digital license",
      "computer programs",
      "pc software",
    ],
    href: "/software-licenses",
    priority: 9,
  },
  {
    id: "en-hardware",
    locale: "en",
    section: "hardware",
    title: "Hardware",
    summary:
      "A section dedicated to equipment, components, accessories and technology products.",
    content:
      "The Hardware section is focused on equipment, components, peripherals and technology accessories. Specific product information, including compatibility, specifications, availability and warranty, should be reviewed on the corresponding product page.",
    keywords: [
      "hardware",
      "equipment",
      "components",
      "computers",
      "pc",
      "laptop",
      "accessories",
      "peripherals",
      "replacement parts",
      "technology products",
    ],
    href: "/hardware",
    priority: 8,
  },
  {
    id: "en-technical-services",
    locale: "en",
    section: "technical-services",
    title: "Technical services",
    summary:
      "Assistance for maintenance, formatting, installation and equipment inspection.",
    content:
      "Fixora includes technical services related to computers and other technology equipment. These services may include preventive maintenance, fault inspection, formatting, optimization and program installation. The final diagnosis and scope depend on the condition and characteristics of each device.",
    keywords: [
      "technical services",
      "maintenance",
      "computer maintenance",
      "formatting",
      "format pc",
      "repair",
      "optimization",
      "install programs",
      "computer inspection",
      "computer support",
    ],
    href: "/technical-services",
    priority: 10,
  },
  {
    id: "en-remote-support",
    locale: "en",
    section: "remote-support",
    title: "Remote support",
    summary:
      "Remote technical assistance for reviewing and resolving software-related problems.",
    content:
      "Remote support allows users to receive technical assistance from a distance when a problem can be reviewed through an authorized connection. It can be useful for configurations, software installation, software errors and technical guidance. Users must authorize the connection and should never share personal passwords, verification codes, session tokens or banking information.",
    keywords: [
      "remote support",
      "remote help",
      "remote assistance",
      "remote control",
      "remote repair",
      "software problems",
      "configuration",
      "distance support",
      "technical guidance",
      "remote support security",
    ],
    href: "/remote-support",
    priority: 10,
  },
  {
    id: "en-plans-promotions",
    locale: "en",
    section: "plans-promotions",
    title: "Plans and promotions",
    summary:
      "A space for checking available packages, benefits and promotions.",
    content:
      "The Plans and Promotions section will display packages, discounts and benefits available through Fixora. Prices, dates, conditions and availability must be checked directly on each published promotion because they may change.",
    keywords: [
      "plans",
      "promotions",
      "offers",
      "discounts",
      "packages",
      "prices",
      "benefits",
      "current promotion",
      "fixora offers",
    ],
    href: "/plans-promotions",
    priority: 8,
  },
  {
    id: "en-accounts-authentication",
    locale: "en",
    section: "help-center",
    title: "Accounts, access and security",
    summary:
      "Guidance for registration, sign-in, email verification, password recovery and administrator access.",
    content:
      "The Fixora assistant can explain how to create a user account, check a public username, sign in, verify an email address and recover a password. Public registration is only for users; administrator accounts are created by the company and require a real email address. The assistant does not register accounts, reserve usernames, sign users in or change passwords. Never send real passwords, six-character codes, private links or session tokens through the chat.",
    keywords: [
      "create account",
      "register",
      "user registration",
      "sign in",
      "log in",
      "access my account",
      "username",
      "public username",
      "username availability",
      "verify email",
      "verification code",
      "resend code",
      "forgot password",
      "recover password",
      "reset password",
      "administrator access",
      "admin account",
      "secure password",
    ],
    priority: 12,
  },
  {
    id: "en-help-center",
    locale: "en",
    section: "help-center",
    title: "Help Center",
    summary:
      "A section for answering common questions about Fixora's products, services, accounts and platform.",
    content:
      "The Help Center is intended to answer frequently asked questions, explain processes and guide users through products, services, purchases, support, accounts and platform features. When a response requires reviewing a specific case, the user should contact Fixora through the Contact section.",
    keywords: [
      "help center",
      "help",
      "frequently asked questions",
      "questions",
      "support",
      "how it works",
      "guidance",
      "information",
      "account help",
      "sign-in problem",
    ],
    href: "/help-center",
    priority: 9,
  },
  {
    id: "en-contact",
    locale: "en",
    section: "contact",
    title: "Contact",
    summary:
      "A channel for specific questions and personalized assistance.",
    content:
      "The Contact section allows users to send questions related to products, resources, licenses, technical services, remote support and account problems that require human review. Official contact details and available communication channels will be displayed in that section. The assistant must not invent phone numbers, email addresses, business hours or locations that have not been published.",
    keywords: [
      "contact",
      "contact fixora",
      "customer service",
      "support agent",
      "phone",
      "email",
      "whatsapp",
      "address",
      "location",
      "personalized assistance",
      "human support",
      "account problem",
    ],
    href: "/contact",
    priority: 10,
  },
] as const satisfies readonly AssistantKnowledgeItem[];